resolution: "480p"
# resolution: "720p"
aspect_ratio: "9:16"
num_frames: 48
fps: 24
frame_interval: 1

seed: 42
multi_resolution: "STDiT2"
dtype: "bf16"
condition_frame_length: 5
align: 5
num_sampling_steps: 30
cfg_scale: 7.0
aes: 6.5

prompt_as_path: true
prompt: [
  'Yellow and black tropical fish dart through the sea.',
  'An epic tornado attacking above aglowing city at night.',
  'Slow pan upward of blazing oak fire in an indoor fireplace.',
  'a cat wearing sunglasses and working as a lifeguard at pool.',
  'Sunset over the sea.',
  'A dog in astronaut suit and sunglasses floating in space.',
]

# speedup
flash_attn: True

# fvd
spatial_skip: True
spatial_threshold: 920
spatial_gap: 2
spatial_block: [8, 25]
temporal_skip: True
temporal_threshold: 920
temporal_gap: 4
cross_skip: True
cross_threshold: 920
cross_gap: 5

# skip diffusion
diffusion_skip: True
diffusion_skip_timestep: [0,0,0,0,0,0,0,1,1,1]