resolution: "480p"
aspect_ratio: "9:16"
num_frames: 48
fps: 24
frame_interval: 1

seed: 42
multi_resolution: "STDiT2"
dtype: "bf16"
condition_frame_length: 5
align: 5
num_sampling_steps: 30
cfg_scale: 7.0
aes: 6.5

prompt_as_path: true
prompt: [
  "Time Lapse of the rising sun over a tree in an open rural landscape, with clouds in the blue sky beautifully playing with the rays of light",
  "The vibrant beauty of a sunflower field. The sunflowers, with their bright yellow petals and dark brown centers, are in full bloom, creating a stunning contrast against the green leaves and stems. The sunflowers are arranged in neat rows, creating a sense of order and symmetry. The sun is shining brightly, casting a warm glow on the flowers and highlighting their intricate details. The video is shot from a low angle, looking up at the sunflowers, which adds a sense of grandeur and awe to the scene. The sunflowers are the main focus of the video, with no other objects or people present. The video is a celebration of nature's beauty and the simple joy of a sunny day in the countryside.",
  "Snow falling over multiple houses and trees on winter landscape against night sky. christmas festivity and celebration concept.",
  "A snowy forest landscape with a dirt road running through it. The road is flanked by trees covered in snow, and the ground is also covered in snow. The sun is shining, creating a bright and serene atmosphere. The road appears to be empty, and there are no people or animals visible in the video. The style of the video is a natural landscape shot, with a focus on the beauty of the snowy forest and the peacefulness of the road.",
  "A serene night scene in a forested area. The first frame shows a tranquil lake reflecting the star-filled sky above. The second frame reveals a beautiful sunset, casting a warm glow over the landscape. The third frame showcases the night sky, filled with stars and a vibrant Milky Way galaxy. The video is a time-lapse, capturing the transition from day to night, with the lake and forest serving as a constant backdrop. The style of the video is naturalistic, emphasizing the beauty of the night sky and the peacefulness of the forest.",
  'An epic tornado attacking above aglowing city at night.',
  'Slow pan upward of blazing oak fire in an indoor fireplace.',
  'Sunset over the sea.',
  'A dog in astronaut suit and sunglasses floating in space.',
  "The niagara river in new york has very rough white water that you aren't allowed raft or kayak",
  "Peru - july 03, 2014: big wave world tour- wave rolling in off the coast of peru.",
  "Waterfall names 'namtok chokkadin' at thong pha phum national park, kanchanaburi province, thailand, panning tilt up in low angle view",
]

# speedup
flash_attn: False  # turn on for faster inference
